### ISSUE TITLE
Default .env-example file contains unused variables

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/cookie-cutter#32]
This file should be recreated with only Masonite 4 env variables, and maybe with a space to separate per config file.
Also some variable do not match variables used in some features.

**Comment by josephmancuso** [comment]
is this still valid?

**Comment by girardinsamuel** [comment]
Yes we should check each configuration file and how they relate to variables defined in .env.

**Comment by girardinsamuel** [comment]
It's linked to the #43 issue
